version: "3"
 
services:
    db_server:
        image: mysql:5.7
        ports:
             - "3306:3306"
        environment:
             - MYSQL_ROOT_PASSWORD=password
             - MYSQL_DATABASE=mydb

    mini-app:
        build: ./api
        ports:
            - 3000:3000
            - 5858:5858
        volumes:
            - ./api:/app
        environment:
            - DB_NAME=mydb
            - DB_HOST=db_server
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=password
        depends_on:
            - db_server
        command: "bash start.sh db_server:3306"

    angular:
        build: ./frontend/
        ports:
            - 4200:4200
            - 49153:49153
        volumes:
            - ./frontend/discord-miniapp/src:/app/src
            - ./frontend/discord-miniapp/start.sh:/app/start.sh
            - /app/src/assets
        depends_on:
            - mini-app
        command: "bash start.sh"
