version: "3"
 
services:
    harmonia_api:
        volumes:
            - ./api:/app
        depends_on:
            - harmonia_db
            - harmonia_redis

    harmonia_angular:
        ports:
            - 4200:4200
        volumes:
            - ./frontend/discord-miniapp/src:/app/src
            - ./frontend/discord-miniapp/start.sh:/app/start.sh
            - /app/src/assets
        depends_on:
            - harmonia_api
        command: "bash start.sh"