version: "3"
 
services:
    mini-app:
        build: ./api
        ports:
            - 3000:3000
            - 5858:5858
        volumes:
            - ./api:/app
        environment:
            - DB_NAME=mydb
            - DB_HOST=db_server
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=password
        depends_on:
            - db_server

    db_server:
       image: mysql:5.7
       ports:
            - "3306:3306"
       environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=mydb